name: section_list_view
description: A ListView like iOS UITableView with Sticky Seciton Header Footer
version: 0.1.2
author: XIAOHENG LIU <xiaoheng.liu@gmail.com>
homepage: https://github.com/xhengx/section_list_view

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sticky_header_footer: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

